app:
  name: 'tgs-service'
  version: '0.0.1'

http:
  port: ':8080'

rcp:
  port: ':9000'

logger:
  log_level: 'debug'

storage:
  type: redis

api:
  type: http
  
redis:
  addr: 'localhost:6379'
  password: ''
  db: 0

token:
  range: 6
