services:
  consul:
    image: hashicorp/consul:1.15.4
    container_name: consul-server
    hostname: consul-server
    restart: always
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS      
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 10.50.0.100
    volumes:
     - ./consul/server.json:/etc/consul.d/server.json:ro
    networks:
      shortener:
        ipv4_address: 10.50.0.100
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -config-dir=/etc/consul.d/"

  # Redis storage for state persistence
  redis:
    image: redis/redis-stack
    restart: always
    container_name: redis-server
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - "redisdata:/data"
    networks:
      shortener:
        ipv4_address: 10.50.0.200
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "ping"]

  # Cassandra storage for state persistence
  cassandra:
    image: cassandra:latest
    restart: always
    container_name: cassandra-server
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - "cassandradata:/var/lib/cassandra"
    networks:
      shortener:
        ipv4_address: 10.50.0.201
    healthcheck:
      test: [ "CMD", "nodetool", "status" ]

  tgs_service:
    restart: on-failure
    build:
      context: ../tgs-service
      dockerfile: ./docker/Dockerfile.consul
      args:
        PORT: $PORT
    dns:
      - 10.50.0.100
    environment:
      - API_TYPE=$API_TYPE
      - REDIS_HOST=10.50.0.200:6379
    networks:
      - shortener
    healthcheck:
      test: grpcurl -plaintext localhost:9000 api.TgsService/Health
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    depends_on:
      redis:
        condition: service_healthy

  shortener_service:
    restart: on-failure
    build:
      context: ../shortener-service
      dockerfile: ./docker/Dockerfile.consul
      args:
        PORT: $PORT
    dns:
      - 10.50.0.100
    environment:
      - API_TYPE=$API_TYPE
      - REDIS_HOST=10.50.0.200:6379
      - DB_HOST=10.50.0.201:9042
      - TGS_SERVICE_URL=tgs.service.consul:9000
      - TGS_SERVICE_TYPE=grpc
    networks:
      - shortener
    healthcheck:
      test: grpcurl -plaintext localhost:9000 api.ShortenerService/Health
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    depends_on:
      tgs_service:
        condition: service_healthy
      redis:
        condition: service_healthy
      cassandra:
        condition: service_healthy
  shortener_web:
    restart: on-failure
    build:
      context: ../shortener-web
      dockerfile: ./docker/Dockerfile.consul
    dns:
      - 10.50.0.100
    ports:  
      - "8080:8080"
    environment:
      - SHORTENER_SERVICE_TYPE=grpc
      - SHORTENER_SERVICE_URL=shortener.service.consul:9000
      - SHORTENER_SERVICE_VERSION=v1
      - APP_DOMAIN=http://127.0.0.1:8080
    networks:
      - shortener
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    depends_on:
      shortener_service:
        condition: service_healthy
networks:
  shortener:
    ipam:
      config:
        - subnet: 10.50.0.0/16
volumes:
  redisdata:
    name: redisdata
  cassandradata:
    name: cassandradata
