app:
  name: 'shortener-service'
  version: '0.0.1'
  domain: 'rjgc.one'

http:
  port: ':8080'

logger:
  log_level: 'debug'

storage:
  type: cassandra
  addr: 'localhost:9042'
  port: '9042'
  password: 'admin'
  user: 'admin'
  db: 'shortener'  

cache_storage:
  type: redis
  filter_name: longsurls
  expire_time_minutes: 60

redis:
  addr: 'localhost:6379'
  password: ''
  db: 0

rate_limiter:
  max_request: 20
  max_request_window_time_seconds: 60

tgs_service:
  adr: "http://localhost:8081/api/v1/next"
  type: http
