// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: tgs.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TgsServiceClient is the client API for TgsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TgsServiceClient interface {
	Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextResponse, error)
	Health(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextResponse, error)
}

type tgsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTgsServiceClient(cc grpc.ClientConnInterface) TgsServiceClient {
	return &tgsServiceClient{cc}
}

func (c *tgsServiceClient) Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextResponse, error) {
	out := new(NextResponse)
	err := c.cc.Invoke(ctx, "/api.TgsService/Next", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgsServiceClient) Health(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextResponse, error) {
	out := new(NextResponse)
	err := c.cc.Invoke(ctx, "/api.TgsService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TgsServiceServer is the server API for TgsService service.
// All implementations must embed UnimplementedTgsServiceServer
// for forward compatibility
type TgsServiceServer interface {
	Next(context.Context, *NextRequest) (*NextResponse, error)
	Health(context.Context, *NextRequest) (*NextResponse, error)
	mustEmbedUnimplementedTgsServiceServer()
}

// UnimplementedTgsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTgsServiceServer struct {
}

func (UnimplementedTgsServiceServer) Next(context.Context, *NextRequest) (*NextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedTgsServiceServer) Health(context.Context, *NextRequest) (*NextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTgsServiceServer) mustEmbedUnimplementedTgsServiceServer() {}

// UnsafeTgsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TgsServiceServer will
// result in compilation errors.
type UnsafeTgsServiceServer interface {
	mustEmbedUnimplementedTgsServiceServer()
}

func RegisterTgsServiceServer(s grpc.ServiceRegistrar, srv TgsServiceServer) {
	s.RegisterService(&TgsService_ServiceDesc, srv)
}

func _TgsService_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgsServiceServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TgsService/Next",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgsServiceServer).Next(ctx, req.(*NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgsService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgsServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TgsService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgsServiceServer).Health(ctx, req.(*NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TgsService_ServiceDesc is the grpc.ServiceDesc for TgsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TgsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.TgsService",
	HandlerType: (*TgsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Next",
			Handler:    _TgsService_Next_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _TgsService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tgs.proto",
}
